# spring.application.name=AsciiGenerationService

# #spring.datasource.url=jdbc:oracle:thin:@10.191.216.58:1522:crsprod
# #spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# #spring.datasource.username=ftwoahm
# #spring.datasource.password=Password@123


# spring.datasource.url=jdbc:oracle:thin:@10.177.103.192:1523/fincorepdb1
# spring.datasource.username=fincore
# spring.datasource.password=Password#1234
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# server.port=8090


# # --- Redis Configuration ---
# spring.data.redis.host=10.0.17.242
# spring.data.redis.port=6379
# spring.cache.type=redis


# app.input.base.path=



spring.application.name=AsciiGenerationService

#spring.datasource.url=jdbc:oracle:thin:@10.191.216.58:1522:crsprod
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=ftwoahm
#spring.datasource.password=Password@123


spring.datasource.url=jdbc:oracle:thin:@10.177.103.192:1523/fincorepdb1
spring.datasource.username=fincore
spring.datasource.password=Password#1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8084


# --- Redis Configuration ---
spring.data.redis.host=10.0.17.242
spring.data.redis.port=6379
spring.cache.type=redis
hadoop.fs.uri=hdfs://10.177.103.199:8022
hadoop.fs.user=root
# hadoop.fs.uri= file:///
# hadoop.fs.user=

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.bootstrap-servers=10.0.19.238:9092
#spring.kafka.bootstrap-servers=kafka-0.kafka.be-test.svc.cluster.local:9092
spring.kafka.consumer.group-id=Airflow_ETL
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
 
spring.kafka.consumer.properties.spring.json.trusted.packages=*
 
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.tcs.fincore.AsciiGenerationService.DTO.ReportGenerationDTO

app.input.base.path=/reports


logging.level.org.apache.kafka=OFF
logging.level.kafka=OFF