REM INSERTING into ASCII_CONFIG
SET DEFINE OFF;
Insert into ASCII_CONFIG (ID,REPORT_ID,FILE_TYPE,OUTPUT_FILE_NAME,OUTPUT_FIRST_LINE,OUTPUT_END_LINE,INPUT_HEAD_COL,INPUT_HEAD_REGEX,OUTPUT_HEAD_COL_PAD,AMOUNT_COL_SEQ,OUTPUT_AMT_COL_LOGIC,OUTPUT_AMT_DECIMAL,OUTPUT_AMT_COL_PAD,OUTPUT_AMT_SIGN,OUTPUT_PER_LINE_HEAD,CREATED_DATE,OUTPUT_INCLUDE_CONDITION) values (101,'nwsa_report','CWP','INR','BWEP1','EPEP',1,'^(?=.{3,5}$)(?:[LAS]\d{1,3}[A-Z]{0,2}|NXY\d{2})$','5L0','3else4','["^S\d{1,3}$|^NXY\d{2}$"][3][/(1000)]','["^S\d{1,3}$|^NXY\d{2}$"][3][ceil]','["^.*"][3][19,2]|["^S\d{1,3}$|^NXY\d{2}$"][3][19,0]','["^.*"][3][NO_SIGN]',4,to_timestamp('09-02-26 12:00:52.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),'["^.*"][3][!=0]|["^.*"][1][ALWAYS]');
Insert into ASCII_CONFIG (ID,REPORT_ID,FILE_TYPE,OUTPUT_FILE_NAME,OUTPUT_FIRST_LINE,OUTPUT_END_LINE,INPUT_HEAD_COL,INPUT_HEAD_REGEX,OUTPUT_HEAD_COL_PAD,AMOUNT_COL_SEQ,OUTPUT_AMT_COL_LOGIC,OUTPUT_AMT_DECIMAL,OUTPUT_AMT_COL_PAD,OUTPUT_AMT_SIGN,OUTPUT_PER_LINE_HEAD,CREATED_DATE,OUTPUT_INCLUDE_CONDITION) values (102,'nwsa_report','WK','INR','BWEP1','EWEP',1,'^(?=.{3,5}$)(?:[LAS]\d{1,3}[A-Z]{0,2}|NXY\d{2})$','5L0','4','["^L\d{1,3}$|^A\d{1,3}$"][4][/1000]','["^L\d{1,3}$|^A\d{1,3}$"][4][round]|["^S\d{1,3}$|^NXY\d{2}$"][4][round]','["^.*"][4][19,0]','["^.*"][4][NO_SIGN]',4,to_timestamp('09-02-26 2:17:48.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),'["^.*"][4][!=0]|["^.*"][1][ALWAYS]');
Insert into ASCII_CONFIG (ID,REPORT_ID,FILE_TYPE,OUTPUT_FILE_NAME,OUTPUT_FIRST_LINE,OUTPUT_END_LINE,INPUT_HEAD_COL,INPUT_HEAD_REGEX,OUTPUT_HEAD_COL_PAD,AMOUNT_COL_SEQ,OUTPUT_AMT_COL_LOGIC,OUTPUT_AMT_DECIMAL,OUTPUT_AMT_COL_PAD,OUTPUT_AMT_SIGN,OUTPUT_PER_LINE_HEAD,CREATED_DATE,OUTPUT_INCLUDE_CONDITION) values (103,'ysa_report',null,'YSA','BYEP1','EYEP',4,'^\d{5}$','5L0','5else6','["^(?!01000$)0[1-9]\d{3}|1\d{4}$"][5][*(-1)]|["^(?!01000$)0[1-9]\d{3}|1\d{4}$"][6][*(-1)]','["^.*"][5][remove_decimal]|["^.*"][6][remove_decimal]','["^.*"][5][18,0]|["^.*"][6][18,0]','["^.*"][5][SHOW_SIGN]|["^.*"][6][SHOW_SIGN]',1,to_timestamp('09-02-26 2:41:46.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null);
Insert into ASCII_CONFIG (ID,REPORT_ID,FILE_TYPE,OUTPUT_FILE_NAME,OUTPUT_FIRST_LINE,OUTPUT_END_LINE,INPUT_HEAD_COL,INPUT_HEAD_REGEX,OUTPUT_HEAD_COL_PAD,AMOUNT_COL_SEQ,OUTPUT_AMT_COL_LOGIC,OUTPUT_AMT_DECIMAL,OUTPUT_AMT_COL_PAD,OUTPUT_AMT_SIGN,OUTPUT_PER_LINE_HEAD,CREATED_DATE,OUTPUT_INCLUDE_CONDITION) values (104,'pnl_report',null,'PL','BPEP1','EPEP',4,'^\d{5}$','5L0','5and1',null,'["^.*"][5][remove_decimal]|["^.*"][1][remove_decimal]','["^.*"][5][18,0]|["^.*"][1][18,0]','["^.*"][5][SHOW_SIGN]|["^.*"][1][SHOW_SIGN]',1,to_timestamp('09-02-26 3:51:09.000000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),null);





REM INSERTING into ASCII_CONFIG_TB
SET DEFINE OFF;
Insert into ASCII_CONFIG_TB (REPORT_ID,HEAD_PATTERN,DESC_PATTERN,SKIP_PATTERN,ASCII_HEADER_ID,ASCII_FOOTER_ID,FILE_IDENTIFIER,ID) values ('ysa_report','COMP','NOMEN',null,'BYPE1','EYEP','TBY',105);
Insert into ASCII_CONFIG_TB (REPORT_ID,HEAD_PATTERN,DESC_PATTERN,SKIP_PATTERN,ASCII_HEADER_ID,ASCII_FOOTER_ID,FILE_IDENTIFIER,ID) values ('pnl_report','FIELD','DESC','Previous','BPEP1','EPEP','TBP',106);
Insert into ASCII_CONFIG_TB (REPORT_ID,HEAD_PATTERN,DESC_PATTERN,SKIP_PATTERN,ASCII_HEADER_ID,ASCII_FOOTER_ID,FILE_IDENTIFIER,ID) values ('nwsa_report','CODE','DESC',null,'BYNW1','EYNW','TBNWSA',107);





REM INSERTING into ASCII_MASTER
SET DEFINE OFF;

Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (101,'NWSA Inner Column ASCII','reports/{date}/ascii_files/nwsa_report','D');
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (102,'NWSA Outer Column ASCII','reports/{date}/ascii_files/nwsa_report','Y');
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (103,'YSA ASCII','reports/{date}/ascii_files/ysa_report','M');
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (104,'PNL ASCII','reports/{date}/ascii_files/pnl_report','M');
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (105,'Trial Balance YSA ASCII','reports/{date}/tb_ascii_files/ysa_report',null);
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (106,'Trial Balance PNL ASCII','reports/{date}/tb_ascii_files/pnl_report',null);
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (107,'Trail Balance NWSA ASCII','reports/{date}/tb_ascii_files/nwsa_report','D');

REM INSERTING PFORM one-line bid amount ASCII config
SET DEFINE OFF;
Insert into ASCII_CONFIG (ID,REPORT_ID,FILE_TYPE,OUTPUT_FILE_NAME,OUTPUT_FIRST_LINE,OUTPUT_END_LINE,INPUT_HEAD_COL,INPUT_HEAD_REGEX,OUTPUT_HEAD_COL_PAD,AMOUNT_COL_SEQ,OUTPUT_AMT_COL_LOGIC,OUTPUT_AMT_DECIMAL,OUTPUT_AMT_COL_PAD,OUTPUT_AMT_SIGN,OUTPUT_PER_LINE_HEAD,CREATED_DATE,OUTPUT_INCLUDE_CONDITION,OUTPUT_LAYOUT) values (108,'pform_report',null,'PFORM','M  000NNN',null,1,'^\d{1,4}$',null,'2','["^.*"][2][/1000]','["^.*"][2][ceil]',null,null,null,SYSTIMESTAMP,null,'PFORM_BID_AMOUNT_SERIES');
Insert into ASCII_MASTER (ID,ASCII_NAME,LOCATION,FREQUENCY) values (108,'PFORM One Line Bid Amount ASCII','reports/{date}/ascii_files/pform_report','M');
